title: Ajay Mohandas
logo: /assets/img/photo.jpeg
description: Data scientist with 4 years of experience at Infosys Limited, specializing in developing impactful data-driven solutions for US clients. Adept in statistical analysis, machine learning, natural language processing and data 
visualization, with a strong technical background in Python, SQL, and Power BI. Proven success in turning complex data into actionable insights, driving positive business outcomes.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
